apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: test
    helm:
      version: v3
      valueFiles:
        - apps-values.yaml
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
