apiVersion: v2
name: inalix
description: Learn helm dev
type: application
version: 0.1.0
dependencies:
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.4
