apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.8.1
    chart: minio
    helm:
      version: v3
      parameters:
      - name: ingress.enabled
        value: "true"
      - name: ingress.hostname
        value: minio-fs.admin.10-11-1-31.nip.io
      - name: persistence.size
        value: 1Gi
      - name: defaultBuckets
        value: "media, backup"
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
