apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.0.1
    chart: redis
    helm:
      version: v3
      valueFiles:
        - _redis-values.yaml

  destination:
    namespace: inalix-system
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
