apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "devel.fullname" . }}-help
  namespace: {{ .Values.systemNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/help/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        image:
          tag: v3
        imagePullSecrets:
          {{- toYaml .Values.imagePullSecrets | nindent 10 }}
        ingress:
          enabled: true
          hosts: 
          - host: {{ .Values.ingressHostname }}
            paths:
              - path: /help/
                pathType: Prefix
  destination:
    namespace: {{ .Values.appNamespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
