apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "inalix.fullname" . }}-webapp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/webapp/
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        image:
          tag: v3-new
        imagePullSecrets:
          {{- toYaml .Values.imagePullSecrets | nindent 10 }}
        ingress:
          enabled: true
          hosts:
          - host: {{ .Values.ingressHostname }}
            paths:
              - path: /
                pathType: Prefix
        env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://redis-master.inalix-system/1 # jb0d8AXz9S
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
