apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "inalix.fullname" . }}-worker
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/worker/
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        image:
          tag: v3-new
        imagePullSecrets:
          {{- toYaml .Values.imagePullSecrets | nindent 10 }}
        ingress:
          enabled: true
          hosts:
          - host: {{ .Values.ingressHostname }}
        env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: {{ .Values.env.REDIS_URL }}
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
