---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgc-aodb
spec:
  instances: 2
  storage:
    size: 2Gi

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: inalix
      owner: inalix
      secret:
        name: inalix-secret

#   monitoring:
#     enablePodMonitor: true

---
apiVersion: v1
data:
  username: aW5hbGl4
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: inalix-secret
type: kubernetes.io/basic-auth


---
apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: SW5hbGl4MTIz
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth
