
syncPolicy:
  selfHeal: true

ingressHostname: "local.gd"

pgadmin4:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: pgadmin.local.gd
        paths:
          - path: /
            pathType: Prefix

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: false
  master:
    persistence:
      size: 1Gi
  replica:
    persistence:
      size: 1Gi

cloudnative-pg:
  enabled: true
  replicaCount: 1

minio:
  enabled: false
  ingress:
    hostname: minio-fs.admin.10-11-1-31.nip.io
  persistence:
    size: 1Gi
  defaultBuckets: "media, backup, static"
