
syncPolicy:
  selfHeal: true

ingressHostname: "local.gd"

pgadmin4:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: pg.admin.local.gd
        paths:
          - path: /
            pathType: Prefix

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: false
  master:
    persistence:
      size: 1Gi
  replica:
    persistence:
      size: 1Gi

cloudnative-pg:
  enabled: true
  replicaCount: 1

minio:
  enabled: false
  mode: distributed

  ingress:
    enabled: true
    hostname: fs.admin.local.gd

  persistence:
    size: 1Gi

  defaultBuckets: "media, backup, static"

  statefulset:
    replicaCount: 2
    zones: 2
    drivesPerNode: 2
