apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aodb
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: lamongan
    helm:
      parameters:
        - name: ingressHostname
          value: aodb-10-11-1-31.nip.io
        - name: targetRevision
          value: lamongan
  destination:
    namespace: inalix-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
