apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: test
    helm:
      parameters:
        - name: repoURL
          value: https://github.com/wahyu-sty/config-example.git
        - name: ingressHostname
          value: test.10-11-1-31.nip.io
        - name: targetRevision
          value: test
        - name: env.REDIS_URL
          value: redis://inalix-system-redis-master.inalix-system/1
        - name: worker.enabled
          value: 'true'
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
