apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: test
    helm:
      version: v3
      values: |
        global:
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
        ingressHotsname: test.10-11-1-31.nip.io
        worker:
          enabled: true
          ingress:
            hostname: test.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
        webapp:
          enabled: true
          ingress:
            hostname: test.10-11-1-31.nip.io
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
        daphne:
          enabled: true
          ingressHotsname: aodb.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/inalix
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
