---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgc-test
spec:
  instances: 3
  storage:
    size: 1Gi

  superuserSecret:
    name: superuser-secret

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: inalix
      owner: inalix
      secret:
        name: inalix-secret

  backup:
    barmanObjectStore:
      destinationPath: "s3://backup/postgresql/"
      endpointURL: http://inalix-system-minio.inalix-system.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-credentials
          key: ACCESS_KEY
        secretAccessKey:
          name: minio-credentials
          key: SECRET_KEY

#   monitoring:
#     enablePodMonitor: true

  managed:
    roles:
      - name: user1
        comment: New user manager by ..
        login: true
        superuser: false
        passwordSecret:
          name: postgres-user1-pass
---
apiVersion: v1
data:
  username: aW5hbGl4
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: inalix-secret
type: kubernetes.io/basic-auth


---
apiVersion: v1
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: superuser-secret
type: kubernetes.io/basic-auth
