apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devel2
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: test
    helm:
      version: v3
      values: |
        ingressHotsname: 

        webapp:
          enabled: true
          ingress:
            enabled: true
            hostname: devel.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/devel
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1

        daphne:
          enabled: true
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/devel
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1

        worker:
          enabled: true
          ingress:
            enabled: false
            hostname: devel.10-11-1-31.nip.io
          env:
          - name: DATABASE_URL
            value: postgres://inalix:password@pgc-inalix-rw.inalix-system/devel
          - name: REDIS_URL
            value: redis://inalix-system-redis-master.inalix-system/1
  destination:
    namespace: devel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
