apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/inalix/
    repoURL: https://github.com/wahyu-sty/config-example.git
    targetRevision: test
    helm:
      version: v3
      values: |
        ingressHotsname: 

        webapp:
          enabled: true
          replicaCount: 2
          imagePullSecrets:
            - name: d-inalix-cred
          image:
            pullPolicy: Always
          ingress:
            enabled: true
            hostname: devel.10-11-1-31.nip.io
        daphne:
          imagePullSecrets:
            - name: d-inalix-cred
          enabled: true
          ingress:
            enabled: true
            hostname: devel.10-11-1-31.nip.io
        worker:
          imagePullSecrets:
            - name: d-inalix-cred
          enabled: true
          ingress:
            enabled: true
            hostname: devel.10-11-1-31.nip.io
  destination:
    namespace: devel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
