apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inalix-help
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://git.inalix.co.id/inalix/docs.git
    targetRevision: v3.help.inalix.com
    helm:
      version: v3
      valueFiles:
        - inalix-help-values.yaml
  destination:
    namespace: devel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
