image:
  tag: v3
imagePullSecrets:
  - name: d-inalix-com-cred
ingress:
  enabled: true
  hosts:
    - host: help.loca.gd
          # help-7f000101.nip.io 
          # help.local.gd
          # help.0a0b0109.nip.io
      paths:
        - path: /
          pathType: Prefix
