apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-console
  namespace: inalix-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.8.1
    chart: minio
    helm:
      version: v3
      values: |
        mode: standalone

        ingress:
          enabled: true
          hostname: console.minio.10-11-1-31.nip.io

        apiIngress:
          enabled: true
          hostname: static.minio.10-11-1-31.nip.io

        persistence:
          size: 1Gi

        defaultBuckets: "media, backup, static"

  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
