apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.fullname" . }}-flower
  labels:
    {{- include "flower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "flower.selectorLabels" . | nindent 4 }}
