# cmd: helm install argocd bitnami/argo-cd --values argocd-values.yaml -n inalix-system --create-namespace
redis:
  architecture: replication
  master:
    persistence:
      size: 1Gi
  replica:
    persistence:
      size: 1Gi
    replicaCount: 2
server:
  ingress:
    enabled: true
    hostname: argocd.10-11-1-31.nip.io
  insecure: true

