# cmd: helm install argocd bitnami/argo-cd --values argocd-values.yaml
redis:
  architecture: replication
  master:
    persistence:
      size: 1Gi
  replica:
    persistence:
      size: 1Gi
    replicaCount: 3
server:
  ingress:
    enabled: true
    hostname: argocd.local.gd
  insecure: true

