apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: daphne-strip-prefix
spec:
  #replacePathRegex:
  #  regex: ^/(?:[^/]+)/(.*)
  #  replacement: /$1
  stripPrefix:
    prefixes:
      - /ws
