apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inalix-help-baru
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: example
    repoURL: https://github.com/wahyu-sty/charts
    targetRevision: v3.help.inalix.com
    helm:
      version: v3
      values: |
        image:
          tag: v3
        imagePullSecrets:
          - name: d-inalix-com-cred
        ingress:
          enabled: true
          hosts:
            - host: baru.0a0b0109.nip.io
              paths:
                - path: /
                  pathType: Prefix

  destination:
    namespace: baru
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
