apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}-static
  labels:
    {{- include "webappstatic.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "webappstatic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webappstatic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: public
          emptyDir:
            sizeLimit: 1Gi
      initContainers:
        - name: {{ .Chart.Name }}-static-init
          image: "d.inalix.com/core:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.inalixSecret }}
            - configMapRef:
                name: {{ .Values.inalixEnv }}
          command:
            - /bin/sh
            - -c
            - |
              echo OK > /srv/http/index.html
              django-admin collectstatic --noinput
              echo OK > /srv/http/static/index.html
          volumeMounts:
            - mountPath: /srv/http/
              name: public
        - name: {{ .Chart.Name }}-static-help
          # image: "d.inalix.com/docs:{{ .Values.image.tag | default .Chart.AppVersion }}"
          image: "d.inalix.com/docs:v3"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              cp -r /www /srv/http/help
          volumeMounts:
            - mountPath: /srv/http/
              name: public
      containers:
        - name: {{ .Chart.Name }}-static
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "nginx:stable"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: public
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
